name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: |
          npm ci
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
      - name: Connect to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -v -i ubuntu@ec2-3-108-194-171.ap-south-1.compute.amazonaws.com 'bash -s' << 'EOF'
            sudo apt-get update
            sudo apt-get install -y nodejs npm 
            sudo npm install -g pm2
            sudo mkdir -p /var/www
            cd /var/www && git clone https://github.com/git-0r/scribble-backend.git
            cd scribble-backend
            npm ci && pm2 stop scribble-backend || true && pm2 start npm --name 'scribble-backend' -- start
          EOF'
