name: Deploy to EC2 using IAM role

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Deploy to EC2
        run: |
          aws ec2-instance-connect send-command --instance-id ${{secrets.EC2_INSTANCE_ID}} --command "sudo apt-get update && sudo apt-get install -y nodejs npm"
          scp -r -o StrictHostKeyChecking=no ./ ec2-3-108-194-171.ap-south-1.compute.amazonaws.com:/var/www/myapp/
          ssh -o StrictHostKeyChecking=no ec2-3-108-194-171.ap-south-1.compute.amazonaws.com 'cd /var/www/myapp/ && npm install --production && pm2 restart myapp'
