name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: |
          npm ci
      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm 
            sudo npm install -g pm2
            sudo mkdir -p app
            cd app && git clone https://github.com/git-0r/scribble-backend.git
            cd scribble-backend
            npm ci && pm2 stop scribble-backend || true && pm2 start npm --name 'scribble-backend' -- start
