name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Build and test
        run: |
          npm ci
      - name: Upload code to EC2 instance
        run: |
          ssh ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p /var/www/myapp"
          scp ${{ secrets.EC2_PRIVATE_KEY }} -r ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/myapp/
      - name: Connect to EC2 instance
        run: |
          ssh ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "sudo apt-get update && sudo apt-get install -y nodejs npm && sudo npm install -g pm2 && cd /var/www/myapp/ && npm install --production && pm2 stop myapp || true && pm2 start npm --name 'myapp' -- start"
